'use client';

import { useState } from 'react';
import { ArrowLeft, Building, TrendingUp, MapPin, DollarSign, Users, AlertTriangle, Target } from 'lucide-react';
import { useRouter } from 'next/navigation';

export default function InvestmentAnalysisPage() {
  const router = useRouter();
  
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Header */}
        <div className="mb-8">
          <button
            onClick={() => router.back()}
            className="inline-flex items-center text-blue-600 hover:text-blue-700 mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </button>
          
          <div className="bg-white rounded-xl shadow-lg p-8">
            <div className="text-center mb-6">
              <h1 className="text-3xl font-bold text-gray-900 mb-2">Investment Analysis Report</h1>
              <p className="text-lg text-gray-600">432 Elm Street, Atlanta, GA</p>
              <p className="text-sm text-gray-500">Generated by MultifamilyOS AI • {new Date().toLocaleDateString()}</p>
            </div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <Target className="h-6 w-6 text-blue-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Executive Summary</h2>
          </div>
          
          <div className="prose max-w-none">
            <p className="text-gray-700 mb-4">
              <strong>Investment Opportunity:</strong> 432 Elm Street presents a compelling value-add multifamily investment opportunity in Atlanta's growing market. This 24-unit property, built in 1995, offers significant upside potential through targeted renovations and operational improvements.
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-6">
              <div className="bg-green-50 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-green-600">18.5%</div>
                <div className="text-sm text-gray-600">Projected IRR</div>
              </div>
              <div className="bg-blue-50 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-blue-600">$2.85M</div>
                <div className="text-sm text-gray-600">Purchase Price</div>
              </div>
              <div className="bg-purple-50 rounded-lg p-4 text-center">
                <div className="text-2xl font-bold text-purple-600">2.2x</div>
                <div className="text-sm text-gray-600">Equity Multiple</div>
              </div>
            </div>

            <div className="bg-blue-50 rounded-lg p-4">
              <h4 className="font-semibold text-blue-900 mb-2">Key Investment Highlights:</h4>
              <ul className="text-blue-800 space-y-1 text-sm">
                <li>• Below-market rents provide immediate value-add opportunity</li>
                <li>• Strong Atlanta submarket with 12% population growth over 5 years</li>
                <li>• Recent comparable sales indicate 15-20% appreciation potential</li>
                <li>• Conservative renovation budget allows for attractive returns</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Property Overview */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <Building className="h-6 w-6 text-purple-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Property Overview</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Physical Description</h4>
              <ul className="space-y-2 text-gray-700">
                <li><strong>Units:</strong> 24 multifamily units</li>
                <li><strong>Year Built:</strong> 1995 (29 years old)</li>
                <li><strong>Square Footage:</strong> 18,000 total sq ft</li>
                <li><strong>Stories:</strong> 3-story walk-up construction</li>
                <li><strong>Parking:</strong> 30 surface parking spaces</li>
                <li><strong>Lot Size:</strong> 0.75 acres</li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Current Operations</h4>
              <ul className="space-y-2 text-gray-700">
                <li><strong>Occupancy:</strong> 92% (22 of 24 units occupied)</li>
                <li><strong>Current Rent Roll:</strong> $28,800/month</li>
                <li><strong>Market Rent Potential:</strong> $32,400/month</li>
                <li><strong>Rent Upside:</strong> 12.5% ($3,600/month)</li>
                <li><strong>Average Rent/Unit:</strong> $1,200 current / $1,350 market</li>
              </ul>
            </div>
          </div>

          <div className="mt-6 p-4 bg-gray-50 rounded-lg">
            <h4 className="font-semibold text-gray-900 mb-2">Value-Add Opportunities</h4>
            <p className="text-gray-700">
              The property offers immediate rent optimization opportunities with current rents averaging $150 below market rate. 
              Planned interior renovations including updated kitchens, bathrooms, and flooring should support premium pricing 
              and reduce vacancy. Additionally, exterior improvements and enhanced landscaping will improve curb appeal and tenant retention.
            </p>
          </div>
        </div>

        {/* Market Analysis */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <MapPin className="h-6 w-6 text-green-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Market Analysis</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Atlanta MSA Overview</h4>
              <ul className="space-y-2 text-gray-700">
                <li><strong>Population:</strong> 6.1M (12% growth, 5-year)</li>
                <li><strong>Median Income:</strong> $71,500 (8% above national)</li>
                <li><strong>Employment Growth:</strong> 15% over 5 years</li>
                <li><strong>Major Employers:</strong> Delta, Coca-Cola, Home Depot</li>
                <li><strong>Unemployment:</strong> 3.2% (below national average)</li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Submarket Dynamics</h4>
              <ul className="space-y-2 text-gray-700">
                <li><strong>Rent Growth:</strong> 8.5% annually (3-year average)</li>
                <li><strong>Vacancy Rate:</strong> 5.2% (healthy market)</li>
                <li><strong>New Supply:</strong> Limited new construction in area</li>
                <li><strong>Walkability:</strong> Excellent transit access</li>
                <li><strong>Demographics:</strong> Young professionals, families</li>
              </ul>
            </div>
          </div>

          <div className="mt-6">
            <h4 className="font-semibold text-gray-900 mb-3">Comparable Properties</h4>
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-4 py-2 text-left">Property</th>
                    <th className="px-4 py-2 text-center">Units</th>
                    <th className="px-4 py-2 text-center">Year Built</th>
                    <th className="px-4 py-2 text-center">Sale Price</th>
                    <th className="px-4 py-2 text-center">Price/Unit</th>
                    <th className="px-4 py-2 text-center">Distance</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  <tr>
                    <td className="px-4 py-2 font-medium">456 Oak Avenue</td>
                    <td className="px-4 py-2 text-center">28</td>
                    <td className="px-4 py-2 text-center">1998</td>
                    <td className="px-4 py-2 text-center">$2,950,000</td>
                    <td className="px-4 py-2 text-center">$105,357</td>
                    <td className="px-4 py-2 text-center">0.8 mi</td>
                  </tr>
                  <tr>
                    <td className="px-4 py-2 font-medium">789 Pine Street</td>
                    <td className="px-4 py-2 text-center">22</td>
                    <td className="px-4 py-2 text-center">1992</td>
                    <td className="px-4 py-2 text-center">$2,650,000</td>
                    <td className="px-4 py-2 text-center">$120,455</td>
                    <td className="px-4 py-2 text-center">1.2 mi</td>
                  </tr>
                  <tr className="bg-green-50">
                    <td className="px-4 py-2 font-medium">432 Elm Street (Subject)</td>
                    <td className="px-4 py-2 text-center">24</td>
                    <td className="px-4 py-2 text-center">1995</td>
                    <td className="px-4 py-2 text-center">$2,850,000</td>
                    <td className="px-4 py-2 text-center">$118,750</td>
                    <td className="px-4 py-2 text-center">—</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Financial Analysis */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <DollarSign className="h-6 w-6 text-yellow-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Financial Analysis</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Acquisition Summary</h4>
              <div className="space-y-2 text-gray-700">
                <div className="flex justify-between">
                  <span>Purchase Price:</span>
                  <span className="font-medium">$2,850,000</span>
                </div>
                <div className="flex justify-between">
                  <span>Closing Costs (3%):</span>
                  <span className="font-medium">$85,500</span>
                </div>
                <div className="flex justify-between">
                  <span>Renovation Budget:</span>
                  <span className="font-medium">$142,500</span>
                </div>
                <div className="flex justify-between border-t pt-2">
                  <span className="font-semibold">Total Investment:</span>
                  <span className="font-semibold">$3,078,000</span>
                </div>
              </div>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Financing Structure</h4>
              <div className="space-y-2 text-gray-700">
                <div className="flex justify-between">
                  <span>Loan Amount (75% LTV):</span>
                  <span className="font-medium">$2,137,500</span>
                </div>
                <div className="flex justify-between">
                  <span>Interest Rate:</span>
                  <span className="font-medium">6.5%</span>
                </div>
                <div className="flex justify-between">
                  <span>Amortization:</span>
                  <span className="font-medium">25 years</span>
                </div>
                <div className="flex justify-between border-t pt-2">
                  <span className="font-semibold">Equity Required:</span>
                  <span className="font-semibold">$940,500</span>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6">
            <h4 className="font-semibold text-gray-900 mb-3">Operating Assumptions</h4>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-gray-50 rounded-lg p-4">
                <div className="text-sm text-gray-600">Annual Rent Growth</div>
                <div className="text-xl font-bold text-gray-900">4.0%</div>
              </div>
              <div className="bg-gray-50 rounded-lg p-4">
                <div className="text-sm text-gray-600">Expense Growth</div>
                <div className="text-xl font-bold text-gray-900">3.0%</div>
              </div>
              <div className="bg-gray-50 rounded-lg p-4">
                <div className="text-sm text-gray-600">Exit Cap Rate</div>
                <div className="text-xl font-bold text-gray-900">6.0%</div>
              </div>
            </div>
          </div>
        </div>

        {/* Returns Analysis */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <TrendingUp className="h-6 w-6 text-blue-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Returns Analysis</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Key Return Metrics</h4>
              <div className="space-y-3">
                <div className="bg-green-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Leveraged IRR</div>
                  <div className="text-2xl font-bold text-green-600">18.5%</div>
                </div>
                <div className="bg-blue-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Equity Multiple</div>
                  <div className="text-2xl font-bold text-blue-600">2.2x</div>
                </div>
                <div className="bg-purple-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Average Annual Return</div>
                  <div className="text-2xl font-bold text-purple-600">16.8%</div>
                </div>
              </div>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Cash-on-Cash Returns</h4>
              <div className="space-y-2 text-gray-700">
                <div className="flex justify-between">
                  <span>Year 1:</span>
                  <span className="font-medium">8.2%</span>
                </div>
                <div className="flex justify-between">
                  <span>Year 3:</span>
                  <span className="font-medium">11.5%</span>
                </div>
                <div className="flex justify-between">
                  <span>Year 5:</span>
                  <span className="font-medium">14.8%</span>
                </div>
                <div className="flex justify-between">
                  <span>Year 10:</span>
                  <span className="font-medium">19.2%</span>
                </div>
              </div>
              
              <div className="mt-4 p-3 bg-blue-50 rounded-lg">
                <h5 className="font-medium text-blue-900 mb-1">10-Year Projection</h5>
                <p className="text-sm text-blue-800">
                  Total cash flow over 10 years plus sale proceeds projects to $2,070,000 
                  return on initial equity investment of $940,500.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Investment Strategy & Exit */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <Users className="h-6 w-6 text-indigo-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Investment Strategy & Exit</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Business Plan</h4>
              <div className="space-y-3">
                <div className="border-l-4 border-blue-500 pl-4">
                  <h5 className="font-medium text-gray-900">Months 1-6: Immediate Improvements</h5>
                  <p className="text-sm text-gray-600">Address deferred maintenance, implement new management systems, optimize leasing</p>
                </div>
                <div className="border-l-4 border-green-500 pl-4">
                  <h5 className="font-medium text-gray-900">Months 6-18: Value-Add Phase</h5>
                  <p className="text-sm text-gray-600">Unit renovations as leases expire, exterior improvements, rent optimization</p>
                </div>
                <div className="border-l-4 border-purple-500 pl-4">
                  <h5 className="font-medium text-gray-900">Years 2-5: Stabilization</h5>
                  <p className="text-sm text-gray-600">Focus on NOI growth, tenant retention, and preparing for exit</p>
                </div>
              </div>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Exit Strategy</h4>
              <div className="space-y-3">
                <div className="bg-gray-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Hold Period</div>
                  <div className="font-medium">5-7 years</div>
                </div>
                <div className="bg-gray-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Projected Exit Value</div>
                  <div className="font-medium">$4,200,000</div>
                </div>
                <div className="bg-gray-50 rounded-lg p-4">
                  <div className="text-sm text-gray-600">Exit Cap Rate</div>
                  <div className="font-medium">6.0%</div>
                </div>
              </div>
              
              <div className="mt-4 p-3 bg-green-50 rounded-lg">
                <h5 className="font-medium text-green-900 mb-1">Value Creation</h5>
                <p className="text-sm text-green-800">
                  Projected NOI growth from $175k to $252k through rent optimization 
                  and operational improvements drives significant value appreciation.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Risk Factors */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8 mb-6">
          <div className="flex items-center mb-4">
            <AlertTriangle className="h-6 w-6 text-red-600 mr-3" />
            <h2 className="text-2xl font-bold text-gray-900">Risk Factors</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Market Risks</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-red-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>Economic Downturn:</strong> Recession could impact rent growth and occupancy rates</span>
                </li>
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-red-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>New Supply:</strong> Potential new construction could increase competition</span>
                </li>
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-red-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>Interest Rates:</strong> Rising rates could affect refinancing and exit valuations</span>
                </li>
              </ul>
            </div>
            
            <div>
              <h4 className="font-semibold text-gray-900 mb-3">Property-Specific Risks</h4>
              <ul className="space-y-2 text-gray-700">
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>Renovation Costs:</strong> Potential cost overruns on improvement projects</span>
                </li>
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>Lease-Up Risk:</strong> Delays in re-leasing renovated units at target rents</span>
                </li>
                <li className="flex items-start">
                  <div className="w-2 h-2 bg-yellow-500 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                  <span><strong>Age of Property:</strong> Potential for unexpected maintenance issues</span>
                </li>
              </ul>
            </div>
          </div>

          <div className="mt-6 p-4 bg-yellow-50 rounded-lg">
            <h4 className="font-semibold text-yellow-900 mb-2">Risk Mitigation Strategies</h4>
            <ul className="text-yellow-800 space-y-1 text-sm">
              <li>• Conservative underwriting with 5% vacancy assumption vs. 2% market average</li>
              <li>• 10% renovation contingency built into budget for unexpected costs</li>
              <li>• Professional property management to minimize operational risks</li>
              <li>• Diversified exit strategy options including refinance or sale</li>
            </ul>
          </div>
        </div>

        {/* Conclusion */}
        <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-8">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">Investment Recommendation</h2>
          
          <div className="bg-green-50 border border-green-200 rounded-lg p-6">
            <div className="flex items-start">
              <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center flex-shrink-0 mr-4">
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                </svg>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-green-900 mb-2">STRONG BUY RECOMMENDATION</h3>
                <p className="text-green-800 mb-4">
                  432 Elm Street represents an exceptional value-add opportunity with attractive risk-adjusted returns. 
                  The combination of below-market rents, strong market fundamentals, and conservative underwriting 
                  supports our projected 18.5% IRR with multiple exit strategies.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div className="text-center">
                    <div className="text-lg font-bold text-green-600">Moderate</div>
                    <div className="text-sm text-green-700">Risk Level</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-bold text-green-600">High</div>
                    <div className="text-sm text-green-700">Return Potential</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-bold text-green-600">5-7 Years</div>
                    <div className="text-sm text-green-700">Optimal Hold</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="mt-6 text-center">
            <p className="text-xs text-gray-500">
              This analysis is generated by MultifamilyOS AI based on property data, market conditions, and financial modeling. 
              All projections are estimates and actual results may vary. Please consult with qualified professionals before making investment decisions.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}